# Copyright (c) 2024 tong<admin>
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

version: '3'

services:
  integrated-documents-projects-nest:
    container_name: 'integrated-documents-projects-nest'
    image: 'integrated-documents-projects-nest:1.0'
    restart: 'always'
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./logs:/home/node/app/logs